# Generated by Django 2.0.3 on 2018-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approbateur',
            fields=[
                ('approbateur', models.CharField(db_column='approbateur', max_length=50)),
                ('approb_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_column='numero')),
                ('fournisseur', models.CharField(db_column='fournisseur', max_length=50)),
                ('date', models.DateField(db_column='date')),
                ('approbateur', models.CharField(db_column='approbateur', max_length=50)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('service', models.CharField(db_column='service', max_length=50)),
                ('activite', models.CharField(db_column='activite', max_length=50)),
                ('montant', models.FloatField(db_column='montant')),
            ],
        ),
    ]
