# Generated by Django 2.0.3 on 2018-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='id',
        ),
        migrations.AddField(
            model_name='contrat',
            name='contrat_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numero',
            field=models.CharField(db_column='numero', max_length=50),
        ),
    ]
