# Generated by Django 2.0.3 on 2018-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180330_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='contrat_id',
        ),
        migrations.AddField(
            model_name='contrat',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
